# Generated by Django 5.1.1 on 2024-10-07 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CONNECTED', 'Connected'), ('TRAINING', 'Training'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20)),
                ('ram', models.FloatField()),
                ('storage', models.FloatField()),
                ('cpu_cores', models.IntegerField(default=0)),
                ('gpu', models.BooleanField(default=False)),
                ('gpu_details', models.CharField(blank=True, max_length=100, null=True)),
                ('subnet', models.CharField(max_length=50)),
                ('last_connected', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
