# Generated by Django 5.1.1 on 2024-10-07 16:47

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_trainingrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),  # Set to null=True
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
