# Generated by Django 5.1.1 on 2024-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_connectionrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
