# Generated by Django 5.1.1 on 2024-10-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_connectionrequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='created_at',
        ),
    ]
