# Generated by Django 5.1.1 on 2024-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_remove_trainingrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
