# Generated by Django 5.1.1 on 2024-10-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_connectionrequest_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='device.device'),
            preserve_default=False,
        ),
    ]
