# Generated by Django 5.1.1 on 2024-10-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_connectionrequest_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='device.device'),
        ),
    ]
